default: &default
  adapter: mysql2
  charset: utf8mb4
  encoding: utf8mb4
  collation: utf8mb4_general_ci
  pool: 5

development:
  <<: *default
  database: todo_card_development
  username: root
  password:

test:
  <<: *default
  database: todo_card_test
  username: root
  password:

production:
  <<: *default
  database: todo_card_production

